### ISSUE TITLE
Getting issue after the app has started

### ISSUE THREAD

**Issue by kanhucd** [dimaportenko/magento-react-native#160]
Getting the below errors after the app has stared. Not sure if its because of Magento. If you could help. The content I have put in the MobileHomePage is only "HomePage". Still getting a JSON parse error. And the content of Block "19" doesnot get displayed on the App may be because of the JSON parse Error may be.

[Thu Nov 19 2020 18:11:37.112]  LOG      {"active": true, "content": "Homepage", "creation_time": "2020-11-19 05:22:18", "id": 19, "identifier": "MHP", "title": "Mobile Homepage", "update_time": "2020-11-19 12:30:59"}
[Thu Nov 19 2020 18:11:37.113]  LOG      {"active": true, **"content": "Homepage"**, "creation_time": "2020-11-19 05:22:18", "id": 19, "identifier": "MHP", "title": "Mobile Homepage", "update_time": "2020-11-19 12:30:59"}
[Thu Nov 19 2020 18:11:37.114]  LOG      [SyntaxError: JSON Parse error: Unexpected identifier "Homepage"]

![image](https://user-images.githubusercontent.com/43762141/99670544-b7ad9700-2a96-11eb-9433-c498201303ed.png)
![image](https://user-images.githubusercontent.com/43762141/99670817-225ed280-2a97-11eb-88b9-340783dc2b52.png)

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.
1. After running the command react-native run-android

**Smartphone (please complete the following information):**
 - Magento Version: 2.3.6
 - Device: Galaxy Pixel 2 API 30
 - OS: Android 
 - Version; 9

**Comment by troublediehard** [comment]
@kanhucd your cms block content should be valid JSON data, check more in the setup instructions https://github.com/troublediehard/magento-react-native#-setup

**Comment by kanhucd** [comment]
@troublediehard Have updated the JSON as suggested by you and getting few other errors now. The banner page is visible now but the other Errors are still appearing.
Have followed the steps and have given the access to ALL for the INtegration user as given in the documentation.
![image](https://user-images.githubusercontent.com/43762141/99818126-d6ce2680-2b73-11eb-86ac-b5715dd74768.png)
![image](https://user-images.githubusercontent.com/43762141/99818163-e0f02500-2b73-11eb-8266-e09743e5d664.png)
![image](https://user-images.githubusercontent.com/43762141/99818244-fa916c80-2b73-11eb-8b7c-80aa13f01a32.png)

**Comment by troublediehard** [comment]
1. Here is wrong value for icon name `ios-arrow-dropright`.
<img width="299" alt="CleanShot 2020-11-21 at 00 29 55@2x" src="https://user-images.githubusercontent.com/6594232/99856056-d5f7bd80-2b90-11eb-8ece-b644bdfc8ca4.png">

2. You are trying access API endpoint which you don't have access to. 
<img width="301" alt="CleanShot 2020-11-21 at 00 30 24@2x" src="https://user-images.githubusercontent.com/6594232/99856192-1c4d1c80-2b91-11eb-9a60-ea8fe72fcb05.png">

**Comment by troublediehard** [comment]
3. `The banner page is visible now but the other Errors are still appearing.` I don't see a banner on your screenshots.

**Comment by kanhucd** [comment]
Hi,

The categories are not showing up though may be because the category Ids filter doesnot work for me some how. Have marked them in yellow in the below screenshot. 
And I have access to ALL in the Integration settings.

![image](https://user-images.githubusercontent.com/43762141/99881647-f7b07d80-2c40-11eb-91b1-b9d4c4f93c92.png)
![image](https://user-images.githubusercontent.com/43762141/99881535-70fba080-2c40-11eb-9320-8ba50ab69107.png)
![image](https://user-images.githubusercontent.com/43762141/99881622-d8b1eb80-2c40-11eb-825f-fa4a5c654ddf.png)

**Comment by troublediehard** [comment]
and what is the response to the following requests?     

<img width="630" alt="CleanShot 2020-11-21 at 20 25 30@2x" src="https://user-images.githubusercontent.com/6594232/99884558-d13a1480-2c37-11eb-97bd-c5d087fb93c8.png">

**Comment by kanhucd** [comment]
Thanks for the insight, I was giving the root category ids. Its loading all the images for me now.

However, the icons donot load for my properly. the arrows on the navigation and the icon at the bottom. Could you please guide me on this.

![image](https://user-images.githubusercontent.com/43762141/100445105-8ce4c380-30d2-11eb-8cbd-7bf6e4b8f26b.png)
![image](https://user-images.githubusercontent.com/43762141/100445192-adad1900-30d2-11eb-9508-b050a4c67e6c.png)
![image](https://user-images.githubusercontent.com/43762141/100445235-bef62580-30d2-11eb-98ad-0ff6292bb038.png)

**Comment by troublediehard** [comment]
I've cloned the project from Github and try to build on the android. I don't see this issue on my end.

The error you see on the screenshot points you that something wrong with `react-native-vector-icons` library. Check if you have the same version as in the git repository `"react-native-vector-icons": "6.6.0",`

![Screenshot_2020-11-28-16-33-09-029_com magento_mobile_app](https://user-images.githubusercontent.com/6594232/100518028-b7e51b00-3197-11eb-81c8-4fccb62930e6.jpg)

**Comment by kanhucd** [comment]
@troublediehard  Thanks for the icons version. It worked.

I am getting Authorization error while signup mostly for the "/rest/default/V1/customers/me" it seems. Could you please help me on this. But the Integration API created has got access to **ALL**.
![image](https://user-images.githubusercontent.com/43762141/100758629-b9bc1200-3415-11eb-95b3-1120f9f872c6.png)
![image](https://user-images.githubusercontent.com/43762141/100759110-42d34900-3416-11eb-88db-ba975772aaf4.png)
![image](https://user-images.githubusercontent.com/43762141/100759986-45826e00-3417-11eb-9c69-f05d5e3b75d3.png)

**Comment by troublediehard** [comment]
hi @kanhucd 
this is API endpoint used customer token, not the admin token that you created for integration. Check it's lifetime settings https://docs.magento.com/user-guide/configuration/services/oauth.html. You have to increase lifetime settings or create reuath logic for the logged customers.

**Comment by kanhucd** [comment]
Hi @troublediehard ,

I tried to increase the lifetime settings but no luck.  Hope I am not missing anything.

![image](https://user-images.githubusercontent.com/43762141/101151735-1a329580-3648-11eb-904c-5ff68dfaec54.png)

**Comment by troublediehard** [comment]
@kanhucd it's hard to say without actual debugging code, but just in case
1. Did you clear the Magento cache? 
2. Did you relogin customer after?

**Comment by kanhucd** [comment]
@troublediehard I am getting this issue while I signup as a new customer.

**Comment by troublediehard** [comment]
@kanhucd also issue can be on the Magento side. And the most straightforward way to find out why the issue happened to debug the backend and see why customer token isn't authorized.
