### ISSUE TITLE
Cart ID

### ISSUE THREAD

**Issue by sidneylopes** [dimaportenko/magento-react-native#167]
When a customer buys something, the old cart still appears, and I have to refresh the app. Is there a way for me to delete the cart id so I can continue buying without the need to refresh the app?

**Comment by troublediehard** [comment]
hi @sidneylopes,

I don't really understand what do you mean by `old cart still appears`. Why do you need a new cart after buy? 

1. Can you share a video with the issue? 
2. Did you reproduce this issue with a clean copy of the current `master` branch of this repository?

**Comment by sidneylopes** [comment]
I won't be able to reproduce it on a fresh copy because, in my version of the app, I need extra payment info to go through with the purchase. Can I record it on my copy?

**Comment by troublediehard** [comment]
@sidneylopes ok, show what you have.

**Comment by sidneylopes** [comment]
Here it is:

https://drive.google.com/file/d/1iQ6PgBXEbZ7S0dab82ot3XKJ-Wc6duli/view?usp=sharing

**Comment by sidneylopes** [comment]
PS: If I restart the app, the cart goes back to empty

**Comment by troublediehard** [comment]
@sidneylopes 
There is `this.props.getCart();` in the `CheckoutTotals.js`. It's supposed to refresh cart data. Try to take look there and check why it's not happening. 

```
// src/components/checkout/CheckoutTotals.js

showPopup(title, message) {
    this.props.checkoutSetActiveSection(1);
    this.props.getCart();
    // this.props.checkoutOrderPopupShown();
    Alert.alert(
      title,
      message,
      [{ text: translate('common.ok'), onPress: () => this.goHome() }],
      { cancelable: false },
    );
  }
```

**Comment by sidneylopes** [comment]
I have the function, but I don't know why the cart doesn't reset

**Comment by troublediehard** [comment]
@sidneylopes sure. It's where developer daily life starts. You should start to debug this functionality. Go to the `getCart` and check each line and variable and try to understand if it's working as expected.

**Comment by sidneylopes** [comment]
okay, I'm gonna try to figure it out. I'll give you feedback on the results.

**Comment by dimaportenko** [comment]
probably solve the issue https://github.com/dimaportenko/magento-react-native/commit/f91d3afa72206ecfaf7f481f5ffd554ed0590fc6
