### ISSUE TITLE
issue faced

### ISSUE THREAD

**Issue by sanjay-baboo299** [dimaportenko/magento-react-native#176]
C:\test\magento-react-native>react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:8044) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 1118 file(s) to forward-jetify. Using 2 workers...
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Launching emulator...
error Failed to launch emulator. Reason: Could not start emulator within 30 seconds..
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :react-native-reanimated
File C:\Users\sanjay.werghis\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Users\sanjay.werghis\AppData\Local\Android\Sdk\licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" ready.
Installing Android SDK Build-Tools 28.0.3 in C:\Users\sanjay.werghis\AppData\Local\Android\Sdk\build-tools\28.0.3
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" complete.
"Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)" finished.
Checking the license for package Android SDK Platform 28 in C:\Users\sanjay.werghis\AppData\Local\Android\Sdk\licenses
License for package Android SDK Platform 28 accepted.
Preparing "Install Android SDK Platform 28 (revision: 6)".
"Install Android SDK Platform 28 (revision: 6)" ready.
Installing Android SDK Platform 28 in C:\Users\sanjay.werghis\AppData\Local\Android\Sdk\platforms\android-28
"Install Android SDK Platform 28 (revision: 6)" complete.
"Install Android SDK Platform 28 (revision: 6)" finished.

> Task :react-native-community_async-storage:compileDebugJavaWithJavac

> Task :react-native-fast-image:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-localize:compileDebugJavaWithJavac

> Task :react-native-reanimated:compileDebugJavaWithJavac

> Task :react-native-screens:compileDebugJavaWithJavac

> Task :react-native-webview:compileDebugJavaWithJavac

> Task :app:compileDebugJavaWithJavac
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libevent-2.1.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfbjni.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfolly_json.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libglog.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjscexecutor.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjsijniprofiler.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libjsinspector.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libnative-filters.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libreactnativeblob.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libreactnativejni.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi\libbugsnag-ndk.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi\libbugsnag-plugin-android-anr.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libc++_shared.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libevent-2.1.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfb.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjsijniprofiler.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libevent_core-2.1.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libevent_extra-2.1.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libglog_init.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes-executor-debug.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes-executor-release.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes-inspector.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjsijniprofiler.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libreactnativejni.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libyoga.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libbugsnag-ndk.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes-executor-debug.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes-executor-release.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes-inspector.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libhermes.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjsijniprofiler.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libreactnativejni.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.

> Task :app:stripDebugDebugSymbols
Compatible side by side NDK version was not found.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libbugsnag-ndk.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libbugsnag-plugin-android-anr.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libc++_shared.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libevent_core-2.1.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libevent_extra-2.1.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfb.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libflipper.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libfolly_futures.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libglog_init.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes-executor-debug.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes-executor-release.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes-inspector.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libhermes.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libimagepipeline.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libnative-imagetranscoder.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libyoga.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libbugsnag-ndk.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libbugsnag-plugin-android-anr.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libevent_core-2.1.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libevent_extra-2.1.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfbjni.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libflipper.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfolly_futures.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libfolly_json.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libglog.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libglog_init.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes-executor-debug.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes-executor-release.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes-inspector.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libhermes.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libimagepipeline.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjscexecutor.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libjsinspector.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libnative-filters.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libnative-imagetranscoder.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libreactnativeblob.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libreactnativejni.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\armeabi-v7a\libyoga.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libbugsnag-ndk.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libbugsnag-plugin-android-anr.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libc++_shared.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libevent-2.1.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfb.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfbjni.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libflipper.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfolly_futures.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libfolly_json.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libglog.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libhermes.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libimagepipeline.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjscexecutor.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libjsinspector.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libnative-filters.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libnative-imagetranscoder.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86\libreactnativeblob.so' due to missing strip tool for ABI 'X86'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libbugsnag-plugin-android-anr.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libc++_shared.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libevent-2.1.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libevent_core-2.1.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libevent_extra-2.1.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfb.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfbjni.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libflipper.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfolly_futures.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libfolly_json.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libglog.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libglog_init.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libimagepipeline.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjscexecutor.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libjsinspector.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libnative-filters.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libnative-imagetranscoder.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libreactnativeblob.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library 'C:\test\magento-react-native\android\app\build\intermediates\merged_native_libs\debug\out\lib\x86_64\libyoga.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.

> Task :app:installDebug
Skipping device 'emulator-5554' (emulator-5554): Device is OFFLINE.

> Task :app:installDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
208 actionable tasks: 208 executed
Note: C:\test\magento-react-native\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: C:\test\magento-react-native\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\test\magento-react-native\node_modules\react-native-localize\android\src\main\java\com\reactcommunity\rnlocalize\RNLocalizeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\test\magento-react-native\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\test\magento-react-native\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\test\magento-react-native\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\test\magento-react-native\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\test\magento-react-native\android\app\src\debug\java\com\magento_mobile_app\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 45s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: C:\test\magento-react-native\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
Note: C:\test\magento-react-native\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\test\magento-react-native\node_modules\react-native-localize\android\src\main\java\com\reactcommunity\rnlocalize\RNLocalizeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\test\magento-react-native\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\test\magento-react-native\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\test\magento-react-native\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\test\magento-react-native\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\test\magento-react-native\android\app\src\debug\java\com\magento_mobile_app\ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No online devices found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11m 45s

    at makeError (C:\test\magento-react-native\node_modules\execa\index.js:174:9)
    at C:\test\magento-react-native\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\test\magento-react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\test\magento-react-native\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by dimaportenko** [comment]
```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:installDebug'.
com.android.builder.testing.api.DeviceException: No online devices found.
```

It's not an issue of the project, you should find out first how to run any React Native project on your environment.
https://www.google.com/search?q=No+online+devices+found&rlz=1C5CHFA_enUA863UA863&oq=No+online+devices+found&aqs=chrome.0.69i59j0.1095j0j7&sourceid=chrome&ie=UTF-8
