### ISSUE TITLE
#<WeakSet> could not be cloned.

### ISSUE THREAD

**Issue by metizror** [dimaportenko/magento-react-native#184]
Using React Native Version 0.64.2 and Having this Error while Running App on the Android.

**Comment by dimaportenko** [comment]
@metizror what error?

**Comment by metizror** [comment]
src/actions/RestActions.js: Program(path) {
      importAll = path.scope.generateUid("$$_IMPORT_ALL");
      importDefault = path.scope.gen...<omitted>... } could not be cloned.

**Comment by dimaportenko** [comment]
Obviously not enough information to investigate what is the issue. But I can guess you haven't followed [setup instructions](https://github.com/dimaportenko/magento-react-native/wiki/Setup#3-installing) and didn't create `src/config/magento.js` correctly.

**Comment by metizror** [comment]
i follow the setup and change the name of the file also,  I got that error while run the app android

**Comment by metizror** [comment]
![Screenshot 2021-06-24 at 3 26 28 PM](https://user-images.githubusercontent.com/8925045/123243345-8ef3f100-d500-11eb-8f9d-0097ac537cd5.png)

**Comment by dimaportenko** [comment]
@metizror looks similar to your issue https://stackoverflow.com/questions/67168197/react-native-run-error-xxx-could-not-be-cloned

**Comment by dimaportenko** [comment]
I've also tested the android debug build on my end and it's working just fine.

**Comment by dimaportenko** [comment]
On your screenshot, I see `package.json` was modified. What did you change?
