### ISSUE TITLE
I found new issue on react native 17.0.1 

### ISSUE THREAD

**Issue by huya03487** [dimaportenko/magento-react-native#187]
src/actions/RestActions.js: #<WeakSet> could not be cloned.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
![image](https://user-images.githubusercontent.com/7591242/124249743-5da5a180-db4e-11eb-8f5b-cc0b33c71a9f.png)

**Comment by dimaportenko** [comment]
hi @huya03487 
I've just done 
```
  git clone https://github.com/dimaportenko/magento-react-native.git
  cd magento-react-native/
  cd ios
  yarn install && pod install
  cd ..
  npx react-native run-ios
  ```
  
 And I don't see the error. 
 Can you provide steps to reproduce your error?
