### ISSUE TITLE
After register firstname returns error

### ISSUE THREAD

**Issue by templatetuners** [dimaportenko/magento-react-native#189]
- magento 2.2.11 

After register, goes into account page with a infinite loading at top instead of name. Returns error 

` ERROR  TypeError: Cannot read property 'firstname' of null, js engine: hermes`

You need to logout and login again

**Comment by dimaportenko** [comment]
@templatetuners can you reproduce it on a clean Magento instance?

**Comment by templatetuners** [comment]
yup, it's clean magento

**Comment by dimaportenko** [comment]
in case it is a remote server instance can you send me your `magento.js` config so I can check it on my end? 

any reason to use such an outdated Magento version?

**Comment by templatetuners** [comment]
going to try later today with newer version of magento. thanks for quick reply
I'll let you know

**Comment by dimaportenko** [comment]
https://devdocs.magento.com/guides/v2.2/release-notes/release-notes-2-2-11-open-source.html

_This release (Magento 2.2.11) marks the final supported software release for Magento version 2.2. Magento 2.2 will no longer receive security updates or product quality fixes now that its support window has expired._

**Comment by templatetuners** [comment]
same with 2.3.2

**Comment by dimaportenko** [comment]
I think I was able to fix it. Try the latest commit from the repository https://github.com/dimaportenko/magento-react-native/commit/890c8886edf68fc931c16f4b9f659eac6b57d7c3. 

Feel free to reopen this ticket.

**Comment by templatetuners** [comment]
That is fixed now.
One more bug :) 
When you go to My address, Region is not autocompleted. 

You can save it if you choose a region than update, but it's blank when you exit the page and get back

**Comment by templatetuners** [comment]
Same for Checkout page, also Country is blank too here

**Comment by dimaportenko** [comment]
@templatetuners please create another issue, I'll take a look later this week

**Comment by dimaportenko** [comment]
screenshots are appreciated
