### ISSUE TITLE
Empty values for Country and Region on address page and checkou

### ISSUE THREAD

**Issue by templatetuners** [dimaportenko/magento-react-native#190]
I type my details in address page, press update than exit. When I get back to page the selectbox for Region is empty.

Similar is happening when I go to checkout, there both Country and Region are empty

![Screenshot_20210823-201442](https://user-images.githubusercontent.com/3463791/130489485-0cbf1cb0-3647-4dd2-bbea-b487a06c9833.png)
![Screenshot_20210823-201430](https://user-images.githubusercontent.com/3463791/130489490-080da277-fa35-4f6d-8e33-179433aa31d1.png)

**Comment by dimaportenko** [comment]
Thank you for the report, I'll be busy the next couple of days. I'll back to it once I have time.

**Comment by dimaportenko** [comment]
@templatetuners check this out ☝️
